### ISSUE TITLE
@acset_colim fails to assign user-defined attribute values

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/DataMigrations.jl#161]
The `@acset_colim` allows us to assign values to certain attributes using the `==` syntax, but this gets broken when one's attribute types are not simple things like `Int` or `Symbol`.

**Comment by ndo885** [comment]
The use of @acset_colim is a key feature elevating the transparency of our health modeling using AlgebraicABMs/AlgebraicRewriting.  However, a preponderance of the health models that we seek to build employ enum-valued attributes (i.e., attributes whose values are delineated by the possible values specified in a @enum construct_. The current inability for @acset_colim to handle such enum-valued attributes leads us to replace @acset_colim uses by those of @acset. 
 This notably impairs the transparency of our existing models -- including in the 5 example models being created in the Categorical ABM hackathon that is currently underway.  I anticipate needing to build a dozen or so models for a full-semester course employing AlgebraicABMs/AlgebraicRewriting that I will be teaching in September, and am very much hoping that we can get @acset_colim supporting @enum values.
